Add test for rename user option in Create User Plugin
cloudbase/cloudbase-init-ci pull request #102
Opened 2017-02-21 15:31 UTC by paulaCrismaru

Rebased over https://github.com/cloudbase/cloudbase-init-ci/pull/97/commits

2017-02-23 18:13 UTC, ader1990 requested changes
This plugins requires its own scenario

2017-03-15 09:30 UTC, stefan-caraiman requested changes
Looks alright, we still need to refactor the way we build recipes in order to have this and the other independent plugins merged.

2017-04-06 09:03 UTC, ader1990 approved these changes

2017-04-06 09:04 UTC, ader1990 approved these changes

2017-04-06 09:04 UTC, merged