Feature/skip decorator
cloudbase/cloudbase-init-ci pull request #104
Opened 2017-02-24 14:36 UTC by micumatei

2017-03-06 13:27 UTC, ader1990 requested changes

2017-03-06 13:27 UTC, ader1990 commented on argus/exceptions.py
> +class ArgusLogicError(ArgusError):
name the error as per the description: ArgusInvalidState

2017-03-06 13:27 UTC, ader1990 commented on argus/exceptions.py
> +class ArgusLogicError(ArgusError):
although I'd put here something like; ArgusInvalidDecorator

2017-03-06 13:27 UTC, ader1990 commented on argus/util.py
> +from argus.tests import base as base_testcase
I would not add a unittest dependecy in the argus utils, as this module should be independent to other modules used in argus

2017-03-06 13:27 UTC, ader1990 commented on argus/util.py
> +                    instance_os_type = get_os_type(target_self)
here we can use duck typing -- if a class has fly method, we can safely say is a flying bird. this way, we can omit the isinstance call and remove the basetestcase dependency

2017-03-06 13:45 UTC, alexcoman requested changes

2017-03-06 13:45 UTC, alexcoman commented on argus/util.py
> +                target_self = kwargs.get("self", args[0])
I don't think that somebody will pass `self=self`. Taking that into consideration we can safely asume that first positional argument is a reference to the instance.

2017-03-06 13:45 UTC, alexcoman commented on argus/util.py
> +                raise exceptions.ArgusLogicError(
I think a warning will be enough. We can return the  wrapped method.

2017-03-08 09:50 UTC, ader1990 requested changes

2017-03-08 09:50 UTC, ader1990 commented on argus/exceptions.py
> +class ArgusInvalidDecorator(ArgusError):
Add an Error suffix to the class name

2017-03-08 09:50 UTC, ader1990 commented on argus/exceptions.py
> +    """Error related to invalid states in the Argus-CI code."""
add a corresponding docstring to the error

2017-03-08 09:50 UTC, ader1990 commented on argus/util.py
> +    return instance._backend.remote_client.manager.os_type
is this the only way to get the OS type? It would be nice to be a public property/getter method

2017-03-15 12:02 UTC, ader1990 requested changes

2017-03-15 12:02 UTC, ader1990 commented on argus/util.py
> +        :param target_os_listos_type: A list with OS version in on which
target_os_list*
in on -> on

2017-03-15 12:02 UTC, ader1990 commented on argus/exceptions.py
> +    """The `skip_on_os` decorator was used improperly."""
Exception triggered when a decorator has been improperly used.

2017-03-15 12:08 UTC, stefan-caraiman commented on argus/util.py
> +    def __init__(self, target_os_list, reason=""):
a default of `Unknown` seems more appropriate than an empty string.

2017-03-15 12:10 UTC, stefan-caraiman commented on argus/util.py
> +            instance_os_type = None
why initialize with `instance_os_type` since the function will return if used incorrectly?

2017-03-15 12:11 UTC, stefan-caraiman commented on argus/exceptions.py
> +class ErrorArgusInvalidDecorator(ArgusError):
shouldn't we keep the same naming convention for argus errors? something like `ArgusInvalidDecoratorError` seems more fit.

2017-03-15 17:31 UTC, ader1990 requested changes

2017-03-15 17:31 UTC, ader1990 commented on argus/util.py
> +    def __init__(self, target_os_list, reason=""):
it s okay like this

2017-03-17 10:49 UTC, ader1990 approved these changes

2017-03-17 10:49 UTC, merged