Feature/arestor
cloudbase/cloudbase-init-ci pull request #116
Opened 2017-04-21 01:43 UTC by micumatei

2017-04-24 10:52 UTC, ader1990 requested changes

2017-04-24 10:52 UTC, ader1990 commented on argus/config/arestor.py
> +# Copyright 2016 Cloudbase Solutions Srl
2017

2017-04-24 10:52 UTC, ader1990 commented on argus/recipes/cloud/windows.py
> +        # HACK(mmicu): for Openstack we have the service_type set to http
Put a note here, no need for hack

2017-04-24 10:52 UTC, ader1990 commented on argus/util.py
> +@contextlib.contextmanager
add the required unit test and all good

2017-05-04 09:26 UTC, ader1990 requested changes

2017-05-04 09:26 UTC, ader1990 commented on argus/config/arestor.py
> +# Copyright 2017 Cloudbase Solutions Srl
Here we need an extensive commit description on what is arestor and why we use arestor and what are the current limitations.

2017-05-04 09:34 UTC, ader1990 requested changes

2017-05-04 09:34 UTC, ader1990 commented on argus/config/arestor.py
> +                help="Delete posted metadata when the scenaro is over."),
typo*

2017-05-04 09:34 UTC, ader1990 commented on argus/backends/windows.py
> +    """Backend Metadata Provider mixing."""
Use metadata consistently and not meta-data.

2017-05-04 09:34 UTC, ader1990 commented on argus/backends/windows.py
> +        base_metadata_provider.BaseMetadataProviderMixing):
BaseMetadataProviderMixin

2017-05-04 09:34 UTC, ader1990 commented on argus/backends/windows.py
> +        """Get a dictionary with post public keys."""
ssh public keys

2017-05-04 09:34 UTC, ader1990 commented on argus/backends/windows.py
> +        """Get the encripted password."""
encrypted*

2017-05-04 09:34 UTC, ader1990 commented on argus/backends/windows.py
> +        """Get a dictionary with post public keys."""
with ssh public keys*

2017-05-04 09:34 UTC, ader1990 commented on argus/backends/windows.py
> +        """Clean up all metadata."""
Prepare or create the metadata

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/__init__.py
> +    return {
put a note here what backend means

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +class ArestorMetadataProviderMixin(base.BaseMetadataProviderMixing):
Mixin*

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +        """Get the encripted password."""
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +        """Get a dictionary with post public keys."""
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +        """Get a dictionary with post public keys."""
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +            client_id="instance-" + backend.instance_server()['name'])
use string formatting

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +        name = instance_server["name"]
use .get instead of []

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +        self._arestor_client.set_uuid(instance_server["id"])
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/base.py
> +class BaseMetadataProviderMixing(object):
Mixin*

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/base.py
> +    """Base class for a MetadataProviderMixing."""
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/base.py
> +        """Get the encripted password."""
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/base.py
> +        """Get a dictionary with post public keys."""
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/base.py
> +        """Get a dictionary with post public keys."""
ditto

2017-05-04 09:34 UTC, ader1990 commented on argus/metadata_provider/base.py
> +        """Clean up all metadata."""
ditto

2017-05-04 09:35 UTC, ader1990 requested changes

2017-05-04 09:35 UTC, ader1990 commented on argus/backends/heat/heat_backend.py
>      def instance_password(self):
encrypted*

2017-05-04 09:36 UTC, ader1990 requested changes
Most of the issues are of naming, typos and quick fixable ones. The big picture seems good.

2017-05-04 21:39 UTC, micumatei commented on argus/util.py
> +@contextlib.contextmanager
Done

2017-05-04 21:39 UTC, micumatei commented on argus/backends/heat/heat_backend.py
>      def instance_password(self):
Done

2017-05-05 10:27 UTC, ader1990 requested changes

2017-05-05 10:27 UTC, ader1990 commented on argus/backends/tempest/manager.py
> +        return encoded_password['password']
use .get

2017-05-05 10:27 UTC, ader1990 commented on argus/backends/windows.py
> +    """Backend Metadata Provider mixing."""
mixin*

2017-05-05 10:27 UTC, ader1990 commented on argus/backends/windows.py
> +        """Get a dictionary with ssh public keys."""
Set*

2017-05-05 10:27 UTC, ader1990 commented on argus/config/arestor.py
> +                help="Delete posted metadata when the scenario is over."),
is finished.

2017-05-05 10:27 UTC, ader1990 commented on argus/metadata_provider/arestor_provider.py
> +        """Get a dictionary with the ssh public keys."""
ditto

2017-05-05 10:27 UTC, ader1990 commented on argus/metadata_provider/base.py
> +        """Get a dictionary with ssh public keys."""
ditto

2017-05-05 10:27 UTC, ader1990 commented on argus/recipes/cloud/base.py
> +        """Create the mocked meta-data."""
metadata*

2017-05-05 10:27 UTC, ader1990 commented on argus/recipes/cloud/base.py
> +        """Delete the mocked meta-data."""
ditto

2017-05-05 10:27 UTC, ader1990 commented on argus/recipes/cloud/windows.py
> +        """Create the mocked meta-data."""
ditto

2017-05-05 10:27 UTC, ader1990 commented on argus/recipes/cloud/windows.py
> +        """Delete the mocked meta-data."""
ditto

2017-05-05 18:33 UTC, micumatei commented on argus/metadata_provider/__init__.py
> +    return {
Done

2017-05-10 11:14 UTC, paulaCrismaru commented on argus/metadata_provider/base.py
> +        """Get a dictionary with ssh hpublic keys."""
public*

2017-05-16 12:21 UTC, ader1990 requested changes

2017-05-16 12:21 UTC, ader1990 commented on argus/config/arestor.py
> +                default="http://0.0.0.0:8080",
default should be localhost: 127.0.0.1 -- you cannot make a request to 0/0, you can only listen at 0/0

2017-05-17 14:30 UTC, ader1990 approved these changes

2017-05-26 08:49 UTC, merged