Improved the git_clone logic
cloudbase/cloudbase-init-ci pull request #31
Opened 2016-08-31 09:26 UTC by dtoncu

2016-08-31 09:28 UTC, alexcoman commented on argus/action_manager/windows.py
> +        del_repo_cmd = ('If (Test-Path -PathType Container -Path '
You should use the python wrapper over `test-path`.

2016-09-02 15:40 UTC, micumatei commented on argus/action_manager/windows.py
> +                            os.path.join(location, ".git")):
You should use `ntpath` not `os.path`

2016-09-02 20:12 UTC, dtoncu commented on argus/action_manager/windows.py
> +                            os.path.join(location, ".git")):
Yes, it is working!

2016-09-05 09:57 UTC, micumatei commented on argus/action_manager/windows.py
>          cmd = "git clone {} {}".format(repo_url, location)
you could use some quotes here for the location parameter.

2016-09-06 08:08 UTC, alexcoman commented on argus/action_manager/windows.py
> +        LOG.info("Trying to clone from %s to \"%s\"", repo_url, location)
Use apostrophe in order to avoid the `\"`.

2016-09-06 08:08 UTC, alexcoman commented on argus/action_manager/windows.py
> +        cmd = "git clone {} \"{}\"".format(repo_url, location)
Ditto.

2016-09-06 08:09 UTC, alexcoman commented on argus/action_manager/windows.py
> +                            os.path.join(location, ".git")):
```python
os.path.join(location, ".git")
``` is useless, if the `location` already exists the `git clone` will fail.

2016-09-06 08:11 UTC, alexcoman commented on argus/action_manager/windows.py
> +                    else:
Is not required because the clone location was chosen by us.

2016-09-06 08:13 UTC, alexcoman commented on argus/action_manager/windows.py
> +            except (socket.error, winrm_exceptions, requests) as exc:
`winrm_exceptions` and `requests` are modules not exeptions.

2016-09-06 10:11 UTC, alexcoman commented on argus/action_manager/windows.py
> +                    self.rmdir(location)
Add a warning here.

2016-09-06 10:11 UTC, alexcoman commented on argus/action_manager/windows.py
> +                    LOG.debug("Failed to clone the repository: %s "
Should be a error message.

2016-09-06 10:13 UTC, alexcoman commented on argus/action_manager/windows.py
> +            except (socket.error, winrm_exceptions.WinRMError,
For `socket.error` and `requests.RequestException` you can catch `exceptions.IOError`.

2016-09-06 10:13 UTC, alexcoman commented on argus/action_manager/windows.py
> +
This new line is not required.

2016-09-06 10:20 UTC, micumatei commented on argus/action_manager/windows.py
> +                              "(return code: %s)" % (stderr, exit_code))
Why do you format the string with `%` when you can let the logger do this.I think you will get a warning when you run this.

2016-09-06 10:21 UTC, micumatei commented on argus/action_manager/windows.py
> +                LOG.debug("Failed to clone the repository: %s" % exc)
Ditto, use the same style `LOG.info('Trying to clone from %s to "%s"...', repo_url, location)` or `LOG.debug("Failed to clone the repository: %s" % exc)`

2016-09-06 13:11 UTC, stefan-caraiman commented
Looks alright, any logs regarding the change? You could also try to make the clone to fail and see if it behaves as expected.

2016-09-06 16:00 UTC, dtoncu commented
2016-08-27 08:08:01,318 - argus - INFO - Trying to clone from https://github.com/dtoncu/cloudbase-init-ci to "C:\cbi-ci"...
2016-08-27 08:08:01,320 - argus - INFO - Running command Test-Path -PathType Any -Path "C:\cbi-ci"...
2016-08-27 08:08:13,332 - argus - INFO - Cloning the repository...
2016-08-27 08:08:38,463 - argus - INFO - The repository was cloned successfully!
---
2016-08-27 08:09:34,886 - argus - INFO - Trying to clone from https://github.com/cloudbase to "C:\cbi-ci"...
2016-08-27 08:09:34,888 - argus - INFO - Running command Test-Path -PathType Any -Path "C:\cbi-ci"...
2016-08-27 08:09:46,754 - argus - INFO - Running command Test-Path -PathType Container -Path "C:\cbi-ci"...
2016-08-27 08:09:58,661 - argus - WARNING - Removing existing repository...
2016-08-27 08:09:58,661 - argus - INFO - Running command Test-Path -PathType Any -Path "C:\cbi-ci"...
2016-08-27 08:10:10,926 - argus - INFO - Running command Test-Path -PathType Container -Path "C:\cbi-ci"...
2016-08-27 08:10:22,948 - argus - DEBUG - Remove directory  C:\cbi-ci
2016-08-27 08:10:22,948 - argus - INFO - Running command Remove-Item -Force -Recurse -Path 'C:\cbi-ci'...
2016-08-27 08:10:34,927 - argus - INFO - Cloning the repository...
2016-08-27 08:10:46,785 - argus - ERROR - Failed to clone the repository: Executing command 'git clone https://github.com/cloudbase "C:\\cbi-ci"' with encoded Command'git clone https://github.com/cloudbase "C:\\cbi-ci"' failed with exit code 128 and output "Cloning into 'C:\\cbi-ci'...\nfatal: repository 'https://github.com/cloudbase/' not found\n".
2016-08-27 08:10:46,785 - argus - DEBUG - Retrying...

2016-09-06 19:45 UTC, alexcoman commented on argus/action_manager/windows.py
> +                    LOG.warn("Removing existing repository...")
Change `...` with `.`.

2016-09-06 19:45 UTC, alexcoman commented on argus/action_manager/windows.py
> +        LOG.info('Trying to clone from %s to "%s"...', repo_url, location)
Change `...` with `.`.

2016-09-06 19:45 UTC, alexcoman commented on argus/action_manager/windows.py
> +                LOG.info("Cloning the repository...")
Change `...` with `.`.

2016-09-06 19:46 UTC, alexcoman commented on argus/action_manager/windows.py
> +            LOG.debug("Retrying...")
Not required.

2016-09-07 08:19 UTC, dtoncu commented on argus/action_manager/windows.py
> +            LOG.debug("Retrying...")
it is not required only this log message?

2016-09-14 15:14 UTC, alexcoman commented on argus/action_manager/windows.py
> +        LOG.info('Trying to clone from %s to "%s"..', repo_url, location)
One dot is enough.

2016-09-14 15:14 UTC, alexcoman commented on argus/action_manager/windows.py
> +        cmd = 'git clone {} "{}"'.format(repo_url, location)
Use named groups.

2016-09-14 15:14 UTC, alexcoman commented on argus/action_manager/windows.py
> +                    LOG.warn("Removing existing repository..")
One dot is enough.

2016-09-14 15:14 UTC, alexcoman commented on argus/action_manager/windows.py
> +                    LOG.warn("Removing existing repository..")
Also use `warning`.

2016-09-14 15:15 UTC, alexcoman commented on argus/action_manager/windows.py
> +                LOG.info("Cloning the repository..")
Ditto.

2016-09-14 15:15 UTC, alexcoman commented on argus/action_manager/windows.py
> +            LOG.debug("Retrying...")
Because is not useful.

2016-09-15 11:24 UTC, alexcoman commented on argus/action_manager/windows.py
> +                    LOG.info("The repository was cloned successfully!")
Change with `... was successfully cloned.`

2016-09-15 11:25 UTC, alexcoman requested changes

2016-09-19 09:36 UTC, alexcoman commented on argus/action_manager/windows.py
> +                if self.exists(location) and self.is_dir(location):
What if the location exists and it's a file ?

2016-09-19 09:36 UTC, alexcoman requested changes

2016-09-21 07:46 UTC, dtoncu commented on argus/action_manager/windows.py
> +                if self.exists(location) and self.is_dir(location):
In this case, git_clone will fail!
But, is it required to treat this case once the clone location was chosen by us?

2016-09-21 12:06 UTC, alexcoman commented on argus/action_manager/windows.py
> +        LOG.info('Trying to clone from %s to "%s".', repo_url, location)
`... to clone %r to ... `

2016-09-21 12:06 UTC, alexcoman commented on argus/action_manager/windows.py
> +                if self.exists(location) and self.is_dir(location):
And it's not a problem if the git clone will fail?

2016-09-21 12:07 UTC, alexcoman requested changes

2016-09-21 15:14 UTC, alexcoman commented
Rephrase the commit description.

2016-09-22 09:23 UTC, alexcoman requested changes
Regarding the commit description.

```
until it times out or succeeds.
```

The command will be executed maximum `util.RETRY_COUNT` times.
Also if the `git-clone` fails with a  time out error the command it will not be executed again ? 

```
This is a better approach since the command was previously failing because of existence of a file/directory with the given name or a lost internet connection.
```

The same idea that

```
a failed git-clone run could left an incomplete repository
```

2016-09-22 13:41 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +                        LOG.warning("Removing existing repository.")
Are these warning really necessary? The logger will get populated with a lot logging messages regarding the deletion of some file or directory, don't think we really need all that.

2016-09-22 13:43 UTC, stefan-caraiman reviewed
The commit message isn't quite right.
Also, could leave\* an incomplete repository, or it's better if you rewrite the whole paragraph to make it more concise.

2016-09-22 13:52 UTC, dtoncu commented on argus/action_manager/windows.py
> +                        LOG.warning("Removing existing repository.")
This warning log message was a request from @alexcoman .

2016-09-23 08:29 UTC, alexcoman commented on argus/action_manager/windows.py
> +                        LOG.warning("Removing existing repository.")
Actually I thinks @stefan-caraiman is right.

2016-09-23 08:29 UTC, alexcoman commented on argus/action_manager/windows.py
> +                        LOG.warning("Removing existing file.")
You can remove this too.

2016-09-23 08:33 UTC, alexcoman commented on argus/action_manager/windows.py
> +                if stderr and exit_code:
This condition will never be `True`.

2016-09-23 08:36 UTC, alexcoman commented on argus/action_manager/windows.py
> +        for _ in range(util.RETRY_COUNT):
Use a `while` loop in order to detect the last iteration, doing so you can avoid an useless sleep.

2016-09-23 08:37 UTC, alexcoman commented on argus/action_manager/windows.py
> +        for _ in range(util.RETRY_COUNT):
See [run_command_with_retry](https://github.com/cloudbase/cloudbase-init-ci/blob/3943ff6fdf1d0a531711d4b9c75d60e29e2c244f/argus/client/windows.py#L237-L250).

2016-09-23 08:38 UTC, alexcoman requested changes
Also the commit message should be changed.

2016-09-23 11:46 UTC, alexcoman commented on argus/action_manager/windows.py
> +        count = 0
It should be `util.RETRY_COUNT`.

2016-09-23 11:46 UTC, alexcoman commented on argus/action_manager/windows.py
> +
This line is not required.

2016-09-23 11:47 UTC, alexcoman commented on argus/action_manager/windows.py
> +
This line is not required.

2016-09-23 11:47 UTC, alexcoman commented on argus/action_manager/windows.py
> +                LOG.info("The repository was successfully cloned!")
Put this code block in the `else` branch of the `try`.

2016-09-23 11:48 UTC, alexcoman commented on argus/action_manager/windows.py
> +                if count == 0:
So it will run until the end of time.

2016-09-23 11:49 UTC, alexcoman commented on argus/action_manager/windows.py
> +                if count >= 0:
This `if` tests if it is the first iteration. Why you need it ?

2016-09-23 11:49 UTC, alexcoman requested changes

2016-09-23 11:52 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +                LOG.info("Cloning the repository.")
Don't think we need to log each clone try since you already log the cloning on line 180.

2016-09-23 11:52 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +
Please delete this blank line.

2016-09-23 11:54 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +
Ditto

2016-09-23 11:54 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +
Ditto, no need for a blank line imo, it's still part of the same logic block.

2016-09-23 11:55 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +                    count -= 1
It will run forever. Please fix.

2016-09-23 12:58 UTC, dtoncu commented on argus/action_manager/windows.py
> +                if count >= 0:
If `count` will be initialized with 0, it will be a infinit while-loop.

2016-09-24 09:59 UTC, alexcoman commented on argus/action_manager/windows.py
> +                if count >= 0:
And that is a very bad thing because if something is wrong with the repo the scenerio will be hanging.

2016-09-24 09:59 UTC, alexcoman requested changes

2016-09-24 11:03 UTC, alexcoman commented
One month and 62 issues reported for this PR are way to much for this task.
The PR will be closed.

2016-09-24 11:03 UTC, closed without merging