Add test scenario to check if swap is enabled
cloudbase/cloudbase-init-ci pull request #51
Opened 2016-10-03 09:22 UTC by stefan-caraiman

Adds a new test scenario for checking whether the swap memory is enabled
on the underlying instance.

2016-10-03 10:07 UTC, ader1990 requested changes

2016-10-03 10:07 UTC, ader1990 commented on argus/introspection/cloud/windows.py
> +        if not stdout:
add a check if stdout equals to ?:\pagefile.sys

2016-10-03 10:07 UTC, ader1990 commented on ci/tests.py
> +
don t create a new scenario, add the test to secnarioimagesmoke

2016-10-03 11:35 UTC, mateimicu requested changes

2016-10-03 11:35 UTC, micumatei commented on argus/introspection/cloud/windows.py
> +        cmd = r'(Get-ItemProperty {}).PagingFiles'.format(swap_query)
This is just a cosmetic thing, but you could have the `swap_query` without single quotes and add them in the `cmd` line . `(Get-ItemProperty '{}')...`

2016-10-03 11:35 UTC, micumatei commented on argus/introspection/cloud/windows.py
> +        if stdout == '?:\pagefile.sys':
Another cosmetic thing `return stdout == '?:\pagefile.sys'`.And you may want to strip the `stdout` something like `return stdout.strip() == '?:\pagefile.sys'`

2016-10-03 11:45 UTC, stefan-caraiman commented on argus/introspection/cloud/windows.py
> +        if stdout == '?:\pagefile.sys':
The stdout can be `None` too if the key has not been found, so the strip approach will fail in that case, unless we first check if it's `None` or not.

2016-10-13 14:16 UTC, ader1990 approved these changes
lgtm

2016-10-13 14:40 UTC, alexcoman requested changes

2016-10-13 14:40 UTC, alexcoman commented on argus/tests/cloud/smoke.py
> +    def test_swap_enabled(self):
Add docstring for this test.

2016-10-13 14:40 UTC, alexcoman commented on argus/tests/cloud/smoke.py
> +class TestSwapEnabled(base.BaseTestCase):
Add docstring.

2016-10-13 14:49 UTC, alexcoman approved these changes

2016-10-13 14:49 UTC, merged