Replace Get-WmiObject and Get-CimInstance calls
cloudbase/cloudbase-init-ci pull request #53
Opened 2016-10-05 00:56 UTC by micumatei

Because we support Windows 2008 and Nano Server we need to choose
between Common Information Model (Cim) and Windows Management
Instrumentation (Wmi) based on the OS type.

Signed-off-by: Micu Matei-Marius <mmicu@cloudbasesolutions.com>

2016-10-07 10:36 UTC, ader1990 reviewed
this will definitely not work with 2008, but this will be subject for another effort

2016-10-07 15:37 UTC, micumatei commented
@ader1990 Agree, this is just one step, that fixes almost all `Get-CimInstace` and `Get-WmiObject` calls, this is needed by Windows 2008 that supports only `Wmi` and by Nano that support only `Cim`. This patch was made with Windows Nano in mind.

2016-10-13 14:24 UTC, ader1990 requested changes
use the already defined constants

2016-10-13 14:24 UTC, ader1990 commented on argus/action_manager/windows.py
> +    cmdlet = "Get-CimInstance" if major_version == 10 else "Get-WmiObject"
you already have the constants defined

2016-10-15 17:29 UTC, alexcoman approved these changes
LGTM

2016-10-15 17:29 UTC, merged