Allow the Action Manager to acces Cloudbase-Init Config
cloudbase/cloudbase-init-ci pull request #56
Opened 2016-10-06 20:31 UTC by micumatei

Signed-off-by: Micu Matei-Marius <mmicu@cloudbasesolutions.com>

2016-10-07 10:33 UTC, ader1990 requested changes
Shouldn't we create a specific action manager for windows nano?

2016-10-07 10:33 UTC, ader1990 commented on argus/action_manager/base.py
>          as side effect.
don't put in the commit message references to yourself

2016-10-13 07:17 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +    # pylint: disable=unused-argument
Is this pragma still required?

2016-10-14 09:44 UTC, micumatei commented on argus/action_manager/base.py
>          as side effect.
Done.

2016-10-14 09:44 UTC, micumatei commented on argus/action_manager/windows.py
> +    # pylint: disable=unused-argument
Still not using `cbinit_conf` or `cbinit_unattend_conf` in this method.

2016-10-15 11:02 UTC, alexcoman commented
LGTM;

2016-10-15 11:04 UTC, alexcoman approved these changes
LGTM

2016-10-15 11:29 UTC, merged