Improve `test_get_console_output` test
cloudbase/cloudbase-init-ci pull request #57
Opened 2016-10-06 20:33 UTC by micumatei

Skip this test if Cloudbase-Init is not set to
log anything to a Serial port.

Signed-off-by: Micu Matei-Marius <mmicu@cloudbasesolutions.com>

2016-10-07 10:30 UTC, ader1990 requested changes

2016-10-07 10:30 UTC, ader1990 commented on argus/tests/cloud/smoke.py
> +        We look in both config objecs to see if `logging_serial_port_settings`
objects*

2016-10-10 10:16 UTC, alexcoman commented on argus/tests/cloud/smoke.py
> +        is_set = (self._recipe._cbinit_conf.conf.has_option(*args) or
Why the `is_set` label is required ?

2016-10-13 14:15 UTC, ader1990 approved these changes
lgtm

2016-10-13 14:25 UTC, merged