Added unit tests for WindowsActionManager class
cloudbase/cloudbase-init-ci pull request #59
Opened 2016-10-12 08:39 UTC by dtoncu

2016-10-13 07:02 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> +        self._os_type = mock.sentinel
mock.sentinel.os_type

2016-10-13 07:11 UTC, stefan-caraiman reviewed
Are `argus/unit_tests/__init__.py` and `argus/unit_tests/action_manager/__init__.py` required in any way?

2016-10-13 07:11 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> +        self._client.run_command_with_retry.side_effect = \
It is preferred to wrap long lines in parentheses and not a backslash for line continuation.

2016-10-13 14:27 UTC, dtoncu commented on argus/unit_tests/action_manager/test_windows.py
> +        self._client.run_command_with_retry.side_effect = \
Ok, but here I don't have parentheses :)

2016-10-13 16:08 UTC, ader1990 commented
looks good to me.

@dtoncu how much is the improvement of coverage?

2016-10-14 07:52 UTC, dtoncu commented
The coverage is at 100% (except tests for `install_cbinit` method -- there are in other PR).

2016-10-14 08:39 UTC, stefan-caraiman requested changes

2016-10-14 08:39 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> +                '.rmdir')
Why are you modifying already existing tests? Please undo these changes.

2016-10-14 08:39 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> +        with self.assertRaises(exceptions.ArgusCLIError):
Please undo these changes, this commit has the purpose to add unit tests, not to rewrite already existing ones.

2016-10-14 08:39 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> +        self.assertFalse(self._action_manager.git_clone(
Ditto.

2016-10-14 08:39 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> -        self.action_manager._client.run_command.return_value = True
Ditto.

2016-10-14 08:39 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> -        mock_sleep.return_value = None
Ditto

2016-10-14 08:40 UTC, stefan-caraiman commented on argus/unit_tests/action_manager/test_windows.py
> +        self._client.run_command_with_retry.side_effect = \
You could wrap the whole lines in parentheses, rather than using a backslash.

2016-10-14 08:54 UTC, stefan-caraiman commented
Please fix failing tests http://paste.openstack.org/show/rPcU6YJceAfizLp1Eej3/

2016-10-14 11:57 UTC, dtoncu commented on argus/unit_tests/action_manager/test_windows.py
> +        with self.assertRaises(exceptions.ArgusCLIError):
I just wanted to be all test in the same style. :)

2016-10-14 12:20 UTC, dtoncu commented on argus/unit_tests/action_manager/test_windows.py
> -        mock_sleep.return_value = None
In this case, there is no need of this line.

2016-10-14 12:21 UTC, dtoncu commented on argus/unit_tests/action_manager/test_windows.py
> -        self.action_manager._client.run_command.return_value = True
You mocked `run_command` to return `True` value but the real `run_command` method will never return `True`.

2016-10-14 14:32 UTC, ader1990 approved these changes
lgtm

2016-10-14 14:35 UTC, merged