Fixed multiple typos
cloudbase/cloudbase-init-ci pull request #63
Opened 2016-10-16 12:31 UTC by dtoncu

This commit fixes typos regarding method docstrings.

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/tests/cloud/windows/test_smoke.py
> -    """Test additional Windows specific behaviour."""
This is a spelling difference(between American and British english) not a typo.

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/introspection/cloud/base.py
> -        """Get the hostname of the instance."""
`hostname` is the right form.

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/introspection/cloud/base.py
> -        """Check if the given username exists in the instance."""
`username` is the right form.

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/recipes/cloud/windows.py
> -        #              how the password should work on next logon,
`logon` is fine.

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/recipes/cloud/windows.py
> -    """Useful for testing the next logon behaviour."""
Ditto

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/recipes/cloud/windows.py
> -    """Always change the password at next logon."""
Ditto

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/recipes/cloud/windows.py
> +    """Change the password at next log on if the password is from metadata."""
Ditto

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/recipes/cloud/windows.py
> -    """Recipe for testing the netbios long hostname compatibility option."""
`hostname` is the right form.

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/tests/cloud/smoke.py
> +    """Test that the expected host-name was set in the instance."""
Ditto

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/tests/cloud/smoke.py
> +        # Verify that the instance host-name matches what we are
Ditto

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/tests/cloud/smoke.py
> -        # Verify that the hostname is set accordingly
Ditto

2016-10-16 19:35 UTC, stefan-caraiman commented on argus/tests/cloud/smoke.py
> -        # Test that the hostname was properly set.
Ditto

2016-10-18 07:34 UTC, stefan-caraiman reviewed
Also please rewrite the commit message like so:

`Fix typos

Fixes typos from docstrings, comments and logging messages.`

2016-10-18 07:34 UTC, stefan-caraiman commented on argus/action_manager/windows.py
>              # Knowing this we have to except this kind of errors.
these kind*

2016-10-18 07:34 UTC, stefan-caraiman commented on argus/scenarios/base.py
> +        # Pylint is not aware that the modules, are reassigned in other
leave it like `attrs`

2016-10-18 07:34 UTC, stefan-caraiman commented on argus/scenarios/base.py
> +        # Pylint is not aware that the attributes are reassigned in other
Ditto

2016-11-04 14:13 UTC, ader1990 requested changes

2016-11-04 14:13 UTC, ader1990 commented on argus/resources/windows/sysprep.ps1
>      # if there is no Unnatended.xml the command will halt and we will never
Unattend.xml

2016-11-04 14:13 UTC, ader1990 commented on argus/resources/windows/installCBinit.ps1
> -    #Cloudbase Init service must start only after the sysprep has rebooted the
spaces after #

2016-11-04 14:34 UTC, stefan-caraiman commented on argus/config_generator/windows/cb_init.py
>              types. The order is important.!
`.!` don't think you need that dot

2016-11-04 14:35 UTC, ader1990 approved these changes

2016-11-04 14:37 UTC, stefan-caraiman commented on argus/scenarios/base.py
> +
is this blank line required?

2016-11-04 15:00 UTC, merged