Refactor unit tests and fix missed docstyle issues
cloudbase/cloudbase-init-ci pull request #65
Opened 2016-10-18 13:48 UTC by stefan-caraiman

WIP

2016-10-19 08:10 UTC, stefan-caraiman commented
The `pylint: disable=wrong-import-order` is required since we are using the `restore_excepthook` method from `argus.utils` when import thirdparty libraries such as the tempest one.

2016-10-19 14:08 UTC, dtoncu commented
LGTM

2016-11-07 17:51 UTC, ader1990 requested changes
there are still 3 lint disables, can you get rid of all of them (if possible)?

2016-11-07 17:51 UTC, ader1990 commented on argus/util.py
> +    """Returns the command decorated acording to the command_type."""
according*

2016-11-07 17:51 UTC, ader1990 commented on argus/unit_tests/action_manager/test_windows.py
> +# pylint: disable=no-value-for-parameter, too-many-lines, protected-access
remove as many pylint disables as possible

2016-11-07 17:51 UTC, ader1990 commented on argus/config_generator/windows/base.py
> +        # pylint: disable=deprecated-method
isn't there another way of handling this?

2016-11-08 10:24 UTC, stefan-caraiman commented on argus/config_generator/windows/base.py
> +        conf.read(base_conf)
Read should only be called after `readfp`, please change it back to `readfp` and find another away if possible to pass the `deprecated-method` warning.

2016-11-08 12:15 UTC, alexcoman requested changes

2016-11-08 12:15 UTC, alexcoman commented on .pylintrc
>  # Specify a configuration file.
Too many not required changes of this file.

2016-11-08 12:15 UTC, alexcoman commented on argus/backends/tempest/tempest_backend.py
>              userdata = base64.encodestring(userdata)
I think this will fail on Python 3.x.

2016-11-08 13:25 UTC, dtoncu commented on argus/backends/tempest/tempest_backend.py
>              userdata = base64.encodestring(userdata)
With the above annotation, it will not. Any suggestion in order to avoid pylint-disable ?

2016-11-09 10:08 UTC, ader1990 approved these changes
lgtm

2016-11-09 19:31 UTC, stefan-caraiman reviewed
LGTM to me, but we need an Argus run for making sure nothing breaks(on both Windows 2012 and 2008), NUC1 should be up to this if needed.

2016-11-15 16:12 UTC, alexcoman approved these changes

2016-11-15 16:13 UTC, alexcoman approved these changes
LGTM;

2016-11-15 16:14 UTC, merged