Add support for Windows 2008
cloudbase/cloudbase-init-ci pull request #67
Opened 2016-10-22 10:33 UTC by stefan-caraiman

WiP

2016-10-31 10:39 UTC, ader1990 requested changes

2016-10-31 10:39 UTC, ader1990 commented on argus/action_manager/windows.py
> +        cmd = ('(New-object System.Net.WebClient).DownloadFile('
New-Object*

We need to check if this works on 2008r2 core

2016-10-31 10:39 UTC, ader1990 commented on argus/action_manager/windows.py
> +class WindowsServer2008R2ActionManager(WindowsActionManager):
afaik, there is no difference on the API on 2008/2008R2, so there is no need to have an action manager for each

2016-10-31 10:39 UTC, ader1990 commented on argus/action_manager/windows.py
>  class WindowsSever2012ActionManager(Windows8ActionManager):
same as above

2016-10-31 10:39 UTC, ader1990 commented on argus/action_manager/windows.py
>      util.WINDOWS_SERVER_2012: WindowsSever2012ActionManager,
ditto

2016-10-31 10:39 UTC, ader1990 commented on argus/introspection/cloud/windows.py
> +def parse_netsh_output(output):
all these netsh commands should be put in one command: parse_netsh_output, which returns a formatted dictionary, like

@{"mtu"=1500;"name"=""}...

2016-10-31 10:39 UTC, ader1990 commented on argus/resources/windows/2008R2/installCBinit.ps1
> +    $WgetUrl = "https://github.com/stefan-caraiman/cloudbase-init-ci/raw/feature/windows-2008/argus/resources/windows/wget.exe"
the download workflow needs to be replaced with a a native command

2016-10-31 10:39 UTC, ader1990 commented on argus/util.py
> +def sanitize_command_output(content):
add some docs on why this happens

2016-11-07 15:51 UTC, ader1990 requested changes
looks good to me, with the change

2016-11-07 15:51 UTC, ader1990 commented on argus/resources/windows/2008R2/installCBinit.ps1
> +    .$curlPath -L $CloudbaseInitMsiUrl --output $CloudbaseInitMsiPath
replace . by &

2016-11-07 16:07 UTC, dtoncu commented on argus/action_manager/windows.py
> +    major_version = introspection.get_os_version(client, 'Major')
I think, it will be better if you will define two constants: `MAJOR` and `MINOR`, and pass as second argument to this function these defines.

2016-11-07 16:15 UTC, dtoncu commented on argus/introspection/cloud/windows.py
> +    result, _, _ = client.run_command_with_retry(cmd, command_type=util.POWERSHELL)
Why not `stdout` instead of `result` ?

2016-11-08 12:09 UTC, merged