Change the get_installation_logs behavior
cloudbase/cloudbase-init-ci pull request #74
Opened 2016-11-29 12:32 UTC by stefan-caraiman

The installation logs will now be archived,
before fetching them from the underlying instance,
in order to avoid longer waiting times.

2016-12-05 13:59 UTC, alexcoman requested changes

2016-12-05 13:59 UTC, alexcoman commented on argus/action_manager/windows.py
> +    def archive_file(self, file_path, destination):
Add docstring.

2016-12-05 13:59 UTC, alexcoman commented on argus/action_manager/windows.py
> +    _ENCODED_SCRIPT = r"C:\encode.py"
For the future development I think a better idea will be to put there a dispatcher.

2016-12-05 13:59 UTC, alexcoman commented on argus/action_manager/windows.py
> +        archive_cmd = 'makecab.exe {source} {dest}'.format(source=file_path,
Why don't you use the `zipfile` module ?

2016-12-05 13:59 UTC, alexcoman commented on argus/action_manager/windows.py
> +    def encode_file_to_base64_str(self, file_path):
Add a docstring please.

2016-12-05 13:59 UTC, alexcoman commented on argus/action_manager/windows.py
> +        self.download_resource("windows/encode.py", self._ENCODED_SCRIPT)
Why don't you put the script there when the recipe is prepared ?

2016-12-05 13:59 UTC, alexcoman commented on argus/recipes/cloud/windows.py
> +    def transfer_encoded_file_b64(encoded_content, path):
Add a docstring please.

2016-12-05 13:59 UTC, alexcoman commented on argus/resources/windows/encode.py
> +def base64_read_file(filepath):
Add a docstring.

2016-12-05 13:59 UTC, alexcoman commented on argus/resources/windows/encode.py
> +# Copyright 2016 Cloudbase Solutions Srl
This can be a collection of utilities. In order to prepare the CLI application you can use argparse (or the `client` module from `arestor` project).

2016-12-06 09:05 UTC, ader1990 commented
Please change the commit message to: Add an option to archive files before winrm transfer

2016-12-06 12:44 UTC, ader1990 requested changes

2016-12-06 12:44 UTC, ader1990 commented on argus/unit_tests/test_utils.py
> +AGENT_RESOURCE_LOCATION = "windows/argusagent.py"
replace with argus_agent

2016-12-06 12:44 UTC, ader1990 commented on argus/unit_tests/test_utils.py
> +AGENT_LOCATION = r"C:\argusagent.py"
ditto

2016-12-06 12:44 UTC, ader1990 commented on argus/action_manager/windows.py
> +    _AGENT_SCRIPT = r"C:\argusagent.py"
replace with argus_agent

2016-12-06 12:44 UTC, ader1990 commented on argus/action_manager/windows.py
> +        Returns a command string formed by the given action and it's
its*

2016-12-06 12:44 UTC, ader1990 commented on argus/introspection/cloud/windows.py
> +                command_type=util.POWERSHELL_SCRIPT_REMOTESIGNED)
use the remote_signed everytime

2016-12-06 12:44 UTC, ader1990 commented on argus/recipes/cloud/windows.py
> +            destination=r"C:\installation.zip")
destination_path*

2016-12-08 15:31 UTC, ader1990 commented on argus/resources/windows/argusagent.py
> +    """Returns a prepareed argument parser."""
typo*

2016-12-08 16:33 UTC, merged