Fix test executable
cloudbase/cloudbase-init-ci pull request #89
Opened 2017-01-10 14:26 UTC by stefan-caraiman

Adds different executables for 32bit and 64bit versions of Windows,
since Windows Nano has been stripped of syswow64 and it isn't able
to run 32bit executable versions.

2017-01-10 14:32 UTC, ader1990 requested changes

2017-01-10 14:32 UTC, ader1990 commented on argus/recipes/cloud/windows.py
> +            resource_location = "windows/test_exe64.exe"
use just one resource_location definition with a formatted string
smth like "arch %s".format(if (arch==amd64)? 64:32)

2017-01-10 14:49 UTC, ader1990 approved these changes
lgtm

2017-01-11 07:11 UTC, micumatei commented
lgtm

2017-01-11 11:10 UTC, ader1990 approved these changes
lgtm

2017-01-11 11:11 UTC, merged