Parameterize the msi and Cloudbase-init location
cloudbase/cloudbase-init-ci pull request #94
Opened 2017-01-18 10:51 UTC by paulaCrismaru

Added parameters for the web location of Cloudbase-init msi and remote repository in the CI config.

2017-01-18 11:02 UTC, stefan-caraiman requested changes

2017-01-18 11:02 UTC, stefan-caraiman commented on argus/recipes/cloud/windows.py
> +_CBINIT_REPO = CONFIG.cbinit_repo
Shouldn't this be `CONFIG.argus.cbinit_repo` ? Don't think it will work otherwise

2017-01-18 11:02 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> +            self._INSTALL_SCRIPT, installer, CONFIG.msi_web_location)
Please fix it to `CONFIG.argus.msi_web_location`

2017-01-18 11:02 UTC, stefan-caraiman commented on argus/action_manager/windows.py
> -        parameters = '-installer {}'.format(installer)
Ditto

2017-01-18 11:02 UTC, stefan-caraiman commented on argus/resources/windows/installCBinit.ps1
> +    [string]$MsiWebLocation,
I think we could add a default value for the `MsiWebLocation` to the previous value `http://www.cloudbase.it/downloads`

2017-01-18 11:02 UTC, stefan-caraiman commented on argus/resources/windows/schedule_installer.ps1
> +    [string]$MsiWebLocation,
Ditto

2017-01-18 14:12 UTC, stefan-caraiman requested changes
Except the naming of the config variables, the patch seems fine, tested it and it seems to work properly.

2017-01-18 14:12 UTC, stefan-caraiman commented on argus/config/ci.py
> +                "cbinit_repo",
I think `remote_repository` or `remote_patch` would be more suggestive

2017-01-18 14:12 UTC, stefan-caraiman commented on argus/config/ci.py
> +                "msi_web_location",
I think `msi_url`/`msi_location` or something similar, since it's not necessarily from the web

2017-01-18 14:19 UTC, ader1990 requested changes

2017-01-18 14:19 UTC, ader1990 commented on argus/config/ci.py
> +                "msi_web_location",
installer_root_url

2017-01-18 14:19 UTC, ader1990 commented on argus/config/ci.py
> +                "cbinit_repo",
cbinit_git_repository

2017-01-18 14:19 UTC, ader1990 commented on argus/resources/windows/schedule_installer.ps1
> +    [string]$MsiWebLocation = 'https://github.com/openstack/cloudbase-init',
leave this as it is

2017-01-26 11:41 UTC, ader1990 approved these changes

2017-01-26 11:46 UTC, merged