Add test and scenario for plugin TRIM
cloudbase/cloudbase-init-ci pull request #96
Opened 2017-02-01 13:13 UTC by micumatei

2017-02-03 11:57 UTC, stefan-caraiman commented on argus/tests/cloud/windows/test_smoke.py
> +        self.assertEqual(True, value)
why not use `self.assertTrue(value)` instead?

2017-02-03 11:58 UTC, stefan-caraiman commented on ci/tests.py
> +class ScenarioSimplePlugins(BaseWindowsScenario):
A more appropriate name would be `ScenarioIndependentPlugins`

2017-02-03 11:59 UTC, stefan-caraiman commented on argus/introspection/cloud/windows.py
> +        command = "fsutil.exe behavior query disabledeletenotify"
A short docstring or note explaining this command would be useful

2017-02-07 11:22 UTC, ader1990 requested changes

2017-02-07 11:22 UTC, ader1990 commented on argus/recipes/cloud/windows.py
> +    """Recipe for testing TRIM manipulation."""
trim configuration*

2017-02-07 11:22 UTC, ader1990 commented on argus/recipes/cloud/windows.py
> +    """Recipe for simple plugins."""
independent plugins*

2017-02-14 11:45 UTC, ader1990 requested changes

2017-02-14 11:45 UTC, ader1990 commented on argus/introspection/cloud/windows.py
> +        return "= 0" in stdout
check if DisableDeleteNotify = 0

2017-02-20 11:43 UTC, ader1990 approved these changes

2017-02-20 11:43 UTC, merged